name: network_image_mock
description: Utility for providing mocked Image.network response in Flutter widget tests.
version: 2.1.2
homepage: https://github.com/stelynx/network_image_mock
repository: https://github.com/stelynx/network_image_mock

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
